#!/bin/bash
#
#                         License
#
# Copyright (C) 2021  David Valin dvalin@redhat.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# This script automates the execution of coremark.  It will determine the
# set of default run parameters based on the system configuration.
#
test_name="passmark"

if [ ! -f "/tmp/${test_name}.out" ]; then
        command="${0} $@"
        echo $command
        $command &> /tmp/${test_name}.out
        cat /tmp/${test_name}.out
        rm /tmp/${test_name}.out
        exit
fi

arguments="$@"

curdir=`pwd`
if [[ $0 == "./"* ]]; then
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	if [[ $chars == 1 ]]; then
		run_dir=`pwd`
	else
		run_dir=`echo $0 | cut -d'/' -f 1-${chars} | cut -d'.' -f2-`
		run_dir="${curdir}${run_dir}"
	fi
else
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	run_dir=`echo $0 | cut -d'/' -f 1-${chars}`
fi

cd $rundir
arch=`uname -m`

show_usage=0

#
# Reduce data
#

summary_file="passmark.summary"
rm $summary_file
pull_data()
{
	passmark_file=`mktemp /tmp/passmark_data.XXXXX`
	test_name=${1}
	grep "^${test_name}" results_all_*yml | cut -d':' -f2 | sed "s/ //g" > ${passmark_file}
	results=0.0
	iterations=0
	while IFS= read -r line
	do
		let "iterations=$iterations+1"
		value=`echo $line | awk '{print $4}'`
		results=`echo "${results}}+${value}"| bc -l`
	done < "${passmark_file}"
	rm ${passmark_file}
	value=`echo "scaling=12;${results}/${iterations}" | bc -l`
	output=`printf "  %s:%-40.12f" $test_name $value | sed "s/ //g" | sed "s/:/: /g"`
	echo "${output}"
}

usage()
{
	echo "$1 Usage:"
	echo "  --cpu_add n: add n cpus each iteration until hit max cpus"
	echo "  --powers_2: starting from 1 cpu, keep doubling the cpus until max cpus"
	source test_tools/general_setup --usage
	exit 0
}

produce_report()
{
	found=0

	if [[ ! -f  results_all_1.yml ]]; then
		echo Failed > test_results_report
	else
		while IFS= read -r line
		do
			if [[ $found -eq 1 ]]; then
				if [[ ${line} != "SystemInformation:"* ]]; then
					test_name=`echo $line | awk '{print $1}'`
					pull_data $test_name
					continue
				else
					found=0
				fi
			fi
			if [[ $line == "NumTestProcesses:"* ]]; then
				found=1
			fi
			echo "${line}" >> $summary_file
		done < "results_all_1.yml"
		echo Ran > test_results_report

		located=0
		while IFS= read -r line
		do
			if [[ $line == *"Results Complete:"* ]]; then
				located=1
				continue
			fi
			if [ $located -eq 0 ]; then
				continue
			fi
			if [[ $line == *"SystemInformation:"* ]]; then
				break;
			fi
			echo $line | sed "s/ //g" >> results.csv
		done < "$summary_file"
	fi
	echo Checksum: Not applicable for summary file >> $summary_file
}

install_tools()
{
	#
	# Clone the repo that contains the common code and tools
	#
	tools_git=https://github.com/redhat-performance/test_tools-wrappers

	found=0
	for arg in "$@"; do
		if [ $found -eq 1 ]; then
			tools_git=$arg
			found=0
		fi
		if [[ $arg == "--tools_git" ]]; then
			found=1
		fi
	
		#
		# We do the usage check here, as we do not want to be calling
		# the common parsers then checking for usage here.  Doing so will
		# result in the script exiting with out giving the test options.
		#
		if [[ $arg == "--usage" ]]; then
			show_usage=1
		fi
	done
	
	#
	# Check to see if the test tools directory exists.  If it does, we do not need to
	# clone the repo.
	#
	if [ ! -d "test_tools" ]; then
		git clone $tools_git test_tools
		if [ $? -ne 0 ]; then
			echo pulling git $tools_git failed.
			exit
		fi
	fi

	if [ $show_usage -eq 1 ]; then
		usage $1
	fi
}

move_data_to_export()
{
	rm -rf /tmp/results_${test_name}_*
	RESULTSDIR=/tmp/results_${test_name}_${to_tuned_setting}_$(date "+%Y.%m.%d-%H.%M.%S")
	mkdir $RESULTSDIR
	mv /tmp/${test_name}.out $RESULTSDIR
	mv test_results_report $RESULTSDIR
	cp ${curdir}/meta_data.yml $RESULTSDIR
	cp passmark.summary $RESULTSDIR
	cp results.csv $RESULTSDIR
	cp results_all_* $RESULTSDIR
	mv  ${test_name}_${iter}.out ${RESULTSDIR}
	pushd /tmp > /dev/null
	ln -s ${RESULTSDIR} results_${test_name}_${to_tuned_setting}
	rm -f results_pbench.tar
	working_dir=`ls -rtd /tmp/results*${test_name}* | grep -v tar | tail -1`
	find -L ${working_dir}  -type f | tar --transform 's/.*\///g' -cf results_pbench.tar --files-from=/dev/stdin
	tar hcf results_${test_name}_${to_tuned_setting}.tar results_${test_name}_${to_tuned_setting}
}

run_passmark()
{
	if [[ -d "/mnt/uploads" ]]; then
		pushd /mnt > /dev/null
	else
		pushd . > /dev/null
	fi
	if [ ! -d "PerformanceTest" ]; then
		if [[ $arch == "aarch64" ]]; then
			uploads/unzip pt_linux_arm64.zip
		else
			uploads/unzip pt_linux_x64.zip
		fi
	fi

	if [ ! -f "/usr/lib64/libncurses.so.5" ]; then
		pushd /usr/lib64 > /dev/null
		ln -s libncurses.so.6 libncurses.so.5
		popd > /dev/null
	fi

	pushd PerformanceTest > /dev/null

	#
	# Iteration of test.
	#

	if [ $to_pbench -eq 0 ]; then
		rm ${test_name}_*out
		rm passmark.summary
		for iter in $(seq 1 1 $to_times_to_run); do
			if [[ $arch == "aarch64" ]]; then
				./pt_linux_arm64 -r 3 >> ${test_name}_${iter}.out
			else
				./pt_linux_x64 -r 3 >> ${test_name}_${iter}.out
			fi
			mv results_all.yml results_all_${iter}.yml
		done
		produce_report
		move_data_to_export
		cp  results_${test_name}_${to_tuned_setting}.tar results_pbench_${test_name}_${to_tuned_setting}.tar
		popd > /dev/null
	else
		source ~/.bashrc
		cd $curdir
		echo $TOOLS_BIN/execute_via_pbench --cmd_executing "$0" $arguments --test ${test_name} --spacing 11 --pbench_stats $to_pstats
		$TOOLS_BIN/execute_via_pbench --cmd_executing "$0" $arguments --test ${test_name} --spacing 11 --pbench_stats $to_pstats
	fi
	popd > /dev/null
}

install_tools "$@"

#
# Variables set by general setup.
#
# TOOLS_BIN: points to the tool directory
# to_home_root: home directory
# to_configuration: configuration information
# to_times_to_run: number of times to run the test
# to_pbench: Run the test via pbench
# to_pbench_copy: Copy the data to the pbench repository, not move_it.
# to_puser: User running pbench
# to_run_label: Label for the run
# to_user: User on the test system running the test
# to_sys_type: for results info, basically aws, azure or local
# to_sysname: name of the system
# to_tuned_setting: tuned setting
#

source test_tools/general_setup "$@"

ARGUMENT_LIST=(
	"cpu_add"
)

NO_ARGUMENTS=(
	"powers_2"
 	"usage"
)

# read arguments
opts=$(getopt \
	--longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
	--longoptions "$(printf "%s," "${NO_ARGUMENTS[@]}")" \
	--name "$(basename "$0")" \
	--options "h" \
	-- "$@"
)

eval set --$opts

while [[ $# -gt 0 ]]; do
	case "$1" in
		--usage)
			usage $0
		;;
		-h)
			usage $0
		;;
		--)
			break
		;;
		*)
			echo option not found $1
			usage $0
		;;
	esac
done

run_passmark
exit 0
